# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waldo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='s3_key',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
