# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('waldo', '0002_photo_s3_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoExifItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('exif_name', models.CharField(blank=True, max_length=100)),
                ('exif_value', models.CharField(blank=True, max_length=1000)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exif_items', to='waldo.Photo')),
            ],
        ),
    ]
