# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waldo', '0003_photoexifitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
    ]
